apiVersion: v1
kind: Pod
metadata:
  name: cpd-install-v52x
  labels:
    app: cpd-install
spec:
  containers:
  - name: olm-utils-v3
    envFrom:
    - configMapRef:
        name: cpd-vars
    env:
    - name: OCP_TOKEN
      valueFrom:
        secretKeyRef:
          name: cpd-token
          key: token
    imagePullPolicy: Always
    image: registry.example.org/docker/cpopen/cpd/olm-utils-v3:latest
    command: ["/bin/sh", "-c"]
    args: 
      - "/opt/ansible/cpd_install.sh"
    volumeMounts:
      - name: olm-utils-storage
        mountPath: /tmp/work
      - name: cpd-install-options
        mountPath: /tmp/work/install-options.yml
        subPath: install-options.yml
      - name: cpd-install-options
        mountPath: /opt/ansible/cpd_install.sh
        subPath: cpd_install.sh
  restartPolicy: Never
  serviceAccount: ibmce-deployment-sa
  volumes:
    - name: olm-utils-storage
      persistentVolumeClaim:
        claimName: olm-utils-storage
    - name: cpd-install-options
      configMap:
        defaultMode: 0755
        name: cpd-install-options
  securityContext:
    fsGroup: 0
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
